import { createRojoProject } from "CLI/util/createRojoProject";
import { getRojoSourceMap, RojoSourceMap } from "CLI/util/getRojoSourceMap";
import fs from "fs-extra";
import path from "path";
import ts from "typescript";
import type yargs from "yargs";

const BANNED_SERVICES = new Set([
	// StarterPlayer contents are cloned elsewhere at runtime and should not be accessed directly
	"StarterPlayer",
	// plugins in the debugger should not be accessed directly
	"PluginDebugService",
]);

function buildSignatures(children: ReadonlyArray<RojoSourceMap>) {
	const seen = new Set<string>();
	const members = new Array<ts.PropertySignature>();
	for (const child of children) {
		if (child.name === "node_modules" || seen.has(child.name)) {
			continue;
		}
		seen.add(child.name);
		members.push(buildPropertySignature(child));
	}
	return members;
}

function buildTypeNode(sourceMap: RojoSourceMap) {
	const types = new Array<ts.TypeNode>();
	types.push(ts.factory.createTypeReferenceNode(sourceMap.className, undefined));
	if (sourceMap.children) {
		types.push(ts.factory.createTypeLiteralNode(buildSignatures(sourceMap.children)));
	}
	return ts.factory.createIntersectionTypeNode(types);
}

function buildPropertySignature(sourceMap: RojoSourceMap) {
	return ts.factory.createPropertySignature(
		undefined,
		ts.isIdentifierText(sourceMap.name, undefined)
			? sourceMap.name
			: ts.factory.createStringLiteral(sourceMap.name),
		undefined,
		buildTypeNode(sourceMap),
	);
}

function buildInterface(name: string, children: ReadonlyArray<RojoSourceMap>) {
	return ts.factory.createInterfaceDeclaration(undefined, name, undefined, undefined, buildSignatures(children));
}

interface TypeGenFlags {
	project: string;
	rojo?: string;
}

export = ts.identity<yargs.CommandModule<object, TypeGenFlags>>({
	command: ["typegen"],

	describe: "Creates a `src/services.d.ts` file from `rojo sourcemap`",

	builder: parser =>
		parser
			.option("project", {
				alias: "p",
				string: true,
				default: ".",
				describe: "project path",
			})
			.option("rojo", {
				string: true,
				describe: "manually select Rojo project file",
			}),

	handler: async argv => {
		const { rojoConfigPath, pathTranslator } = createRojoProject(argv);
		const rojoSourceMap = getRojoSourceMap(rojoConfigPath, true);

		const statements = new Array<ts.Statement>();

		if (rojoSourceMap.children) {
			for (const service of rojoSourceMap.children) {
				if (BANNED_SERVICES.has(service.className) || !service.children) {
					continue;
				}

				const children = service.children.filter(child => {
					if (
						service.className === "Workspace" &&
						child.name === "Terrain" &&
						child.className === "Terrain"
					) {
						// Workspace.Terrain already has a fixed type, so add its children to Terrain itself
						if (child.children) {
							statements.push(buildInterface("Terrain", child.children));
						}
						return false;
					}
					return true;
				});
				statements.push(buildInterface(service.className, children));
			}
		}

		if (statements.length > 0) {
			statements[0] = ts.setSyntheticLeadingComments(statements[0], [
				{
					text: " eslint-disable -- This file is generated by rbxtsc ",
					pos: -1,
					end: -1,
					hasTrailingNewLine: true,
					kind: ts.SyntaxKind.MultiLineCommentTrivia,
				},
			]);
		}

		const sourceFile = ts.factory.createSourceFile(
			statements,
			ts.factory.createToken(ts.SyntaxKind.EndOfFileToken),
			ts.NodeFlags.None,
		);

		const printer = ts.createPrinter({});
		const fileContents = printer.printFile(sourceFile);
		const filePath = path.join(pathTranslator.rootDir, "services.d.ts");
		fs.ensureDirSync(path.dirname(filePath));
		fs.writeFileSync(filePath, fileContents);
	},
});
