name: Publish @next

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

jobs:
  publish:
    if: github.repository == 'roblox-ts/roblox-ts' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: Install NPM Dependencies
        uses: bahmutov/npm-install@v1

      - name: Publish @next
        run: |
          git config user.name "GitHub Actions"
          git config user.email "noreply@github.com"
          echo "//registry.npmjs.org/:_authToken=${{ secrets.npm_token }}" > .npmrc
          npm version --no-git-tag-version $(cat package.json | jq -r .version)-dev-$(git rev-parse --short HEAD)
          npm publish --tag next
