name: Publish
run-name: Publish ${{ inputs.version }} (@${{ github.actor }})

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  publish:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.pat }}


      - uses: actions/setup-node@v4
        with:
            node-version: "20.x"
            registry-url: "https://registry.npmjs.org"

      - name: Install NPM Dependencies
        uses: bahmutov/npm-install@v1

      - name: Publish
        run: |
          git config user.name "GitHub Actions"
          git config user.email "noreply@github.com"
          npm version ${{ inputs.version }}
          npm publish --provenance
          git push
          git push --tags
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
